.PHONY: test
test:
	@echo "Running tests..."

run:
	python process_reviews.py --input test_reviews.jsonl --inappropriate_words data/inappropriate_words.txt --output data/filtered_reviews.jsonl --aggregations data/aggregations.jsonl