.PHONY: test
test:
	@echo "Running tests..."

process:
	python code/process_reviews.py --input data/reviews.jsonl --inappropriate_words data/inappropriate_words.txt --output data/filtered_reviews.jsonl --aggregations data/aggregations.jsonl