.PHONY: run
run:
	python ./code/process_content_images.py --images ./data/images.jsonl --tags ./data/image_tags.jsonl --main_images ./data/main_images.jsonl --output_cdc ./cdc/cdc --output_snapshot ./snapshot/snapshot --output_metrics ./metrics/metrics


.PHONY: test
test:
	@echo "Running tests..."